config/routes.rb
ClimatizanetT2::Application.routes.draw do
  
  resources :equipamentos

  resources :orcamentos do
    resources :items
  end

  resources :items

  resources :orcamentos

  resources :clientes

  resources :usuarios

  resources :clientes do
    resources :agendas
  end

  resources :clientes do
    resources :orcamentos
  end

  
  resources :agendas

  resource :user_sessions, only: [:create, :new, :destroy]

  root 'home#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	belongs_to :usuario
	has_many :orcamentos
	has_many :agendas
	validates_presence_of :nome, :email, :telefone

	paginates_per 3


	def self.search(query)
		if query.present?
			where(['email ILIKE :query or
				nome ILIKE :query or
				celular ILIKE :query', query: "%#{query}%"])
		else
			scoped
		end
	end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :require_authentication, only: [:index, :new, :edit, :show, :create, :update, :destroy]

  def index
    @search_query = params[:q]

    @clientes = usuario_corrente.clientes.search(@search_query).page params[:page]

  end

  def show
    @cliente = usuario_corrente.clientes.find(params[:id]) 
  end

  def new
    @cliente = usuario_corrente.clientes.build
  end

  def edit
    @cliente = usuario_corrente.clientes.find(params[:id])    
  end

  def create
    #poderia ser assim...  @cliente = Cliente.new(params[:user])  usando mass-assignment, pag.64
    @cliente = usuario_corrente.clientes.build(cliente_params)

    if @cliente.save
      #O métodoredirect_toenvia ao browser do usuário um código de resposta
      #“302” que signi!ca “Moved Temporarily”, dizendo ao navegador que ele deve ir para
      #outro endereço. tambem estamos escrevendo uma mensagem via "flash", 
      # Quando você escreve no flash, o conteúdo só estará disponível na próxima requisição. Por isso, é
      #normalmente utilizado em conjunto com redireções.
      redirect_to @cliente, notice: 'Cliente criado com sucesso!'
    else
      #redirecionar, perdemos todos os parâmetros que o usuário enviou e também as mensagens
      #de erro de validação quando executamos o método #save. Para essas
      #situações, devemos usar o#render, que não causa o redirecionamento.
      render action: 'new'
    end
  end

  def update
    @cliente = usuario_corrente.clientes.find(params[:id])

    if @cliente.update(cliente_params)
      redirect_to @cliente, notice: 'Cliente alterado com sucesso!'
    else
      render action: 'edit'
    end
  end

  def destroy
    @cliente = usuario_corrente.clientes.find(params[:id])
    @cliente.destroy
      redirect_to clientes_url
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    #proteção para mass-assignment
    def cliente_params
      params.require(:cliente).permit(:nome, :email, :cep, :endereco, :bairro, :municipio, :estado, :telefone, :celular, :cpf, :rg, :info)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<!--O componente de templates do Rails (ActionView) possui um recurso chamadopartials, que são mini-templates 
que podem ser embutidos em outros templates, ou seja, umapartialnão é usada para renderizar diretamente uma ação,
 mas é usada para compor um pequeno pedaço de uma página. -->

<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2> Erro ao salvar registro! Favor verificar. </h2>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nome" %>
    <%= f.text_field :nome %>
    <%= error_tag @cliente, :nome %>
  </div>
  <div class="field">
    <%= f.label "E-mail" %>
    <%= f.text_field :email %>
    <%= error_tag @cliente, :email %>
  </div>

  <div class="campo-left">
    <%= f.label "CEP" %>
    <%= f.text_field :cep %>
    <%= error_tag @cliente, :cep %>
  </div>
  <div class="campo-rigth">
    <%= f.label "Endereço" %>
    <%= f.text_field :endereco %>
    <%= error_tag @cliente, :endereco %>
  </div>


  <div class="campo-left">
    <%= f.label "Bairro" %>
    <%= f.text_field :bairro %>
    <%= error_tag @cliente, :bairro %>
  </div>
  <div class="campo-rigth">
    <%= f.label "Município" %>
    <%= f.text_field :municipio %>
    <%= error_tag @cliente, :municipio %>
  </div>

  <div class="field">
    <%= f.label "Estado" %>
    <%= f.text_field :estado %>
    <%= error_tag @cliente, :estado %>
  </div>

  <div class="campo-left">
    <%= f.label "Telefone" %>
    <%= f.text_field :telefone %>
    <%= error_tag @cliente, :telefone %>
  </div>
  <div class="campo-rigth">
    <%= f.label "Celular" %>
    <%= f.text_field :celular %>
    <%= error_tag @cliente, :celular %>
  </div>
  
  <div class="campo-left">
    <%= f.label "CPF" %>
    <%= f.text_field :cpf %>
    <%= error_tag @cliente, :cpf %>
  </div>
  <div class="campo-rigth">
    <%= f.label "RG" %>
    <%= f.text_field :rg %>
    <%= error_tag @cliente, :rg %>
  </div>
  <div class="field">
    <%= f.label "Informações Adicionais" %>
    <%= f.text_area :info %>
    <%= error_tag @cliente, :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/_search.html.erb
<%= form_tag clientes_path, method: :get, class: 'search' do %>
  <%= text_field_tag :q, @search_query,
    placeholder: 'Buscar por...' %>
<% end%>

app/views/clientes/edit.html.erb
<h1>Editar cliente</h1>

<%= render 'form' %>

<!-- NOTA: Na ação edit usamos a capacidade do Rails de determinar a rota de
show de um recurso, apenas colocando o objeto como parâmetro. -->
<%= link_to 'Voltar', @cliente,  class: "action_button"%> 

app/views/clientes/index.html.erb
<%= render 'search' %>

<h1> 
  <% if @search_query.present? %>
    Resultados da busca
  <% else  %>
    Clientes
  <% end %>
</h1>

<% @clientes.each do |cliente| %>
  <article class="cliente">
    <p>
      <h2><%= link_to highlight(cliente.nome || '', @search_query), cliente , id: "titleArt",  class: "titleArt" %></h2>
        <p class="created">
          <%= highlight(cliente.email || '', @search_query) %>
        </p>
        <p class="created">
          <%= highlight(cliente.telefone || '', @search_query)%>
        </p>
        <p class="created">
          <%= highlight(cliente.celular || '', @search_query) %>
        </p>
        <p class="created">
          <%= highlight(cliente.cpf || '', @search_query) %>
        </p>
    </p>
        <t><%= link_to 'Mostrar', cliente , class: "action_button" %></t>
        <t><%= link_to 'Editar', edit_cliente_path(cliente) , class: "action_button" %></t>
        <t><%= link_to 'Excluir', cliente, method: :delete, data: { confirm: 'Você realmente deseja excluir?' }, class: "action_button" %></t>
  </article>
<% end %>

<%= paginate @clientes %>

</br>

<%= link_to 'Novo', new_cliente_path ,  id: "newButton",  class: "newButton"%>

app/views/clientes/new.html.erb
<h1>Novo cliente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', clientes_path, class: "action_button"%>

app/views/clientes/show.html.erb
<p >
  <h3 id="title" class="title"><%= @cliente.nome %> </h3>
</p>

<table id="showTable" class="showTable">
  <tr>
    <td><strong>Endereco:</strong></td>
    <td><%= @cliente.endereco %></td>
  </tr>

  <tr>
    <td><strong>Cep:</strong></td>
    <td><%= @cliente.cep %></td>
  </tr>

  <tr>
    <td><strong>Email:</strong></td>
    <td><%= @cliente.email %></td>
  </tr>

  <tr>
    <td><strong>Bairro:</strong></td>
    <td><%= @cliente.bairro %></td>
  </tr>

  <tr>
    <td><strong>Municipio:</strong></td>
    <td><%= @cliente.municipio %></td>
  </tr>

  <tr>
    <td><strong>Estado:</strong></td>
    <td><%= @cliente.estado %></td>
  </tr>

  <tr>
    <td><strong>Telefone:</strong></td>
    <td><%= @cliente.telefone %></td>
  </tr>

  <tr>
    <td><strong>Celular:</strong></td>
    <td><%= @cliente.celular %></td>
  </tr>

  <tr>
    <td><strong>Cpf:</strong></td>
    <td><%= @cliente.cpf %></td>
  </tr>

  <tr>
    <td><strong>Rg:</strong></td>
    <td><%= @cliente.rg %></td>
  </tr>

  <tr>
    <td><strong>Info:</strong></td>
    <td><%= @cliente.info %></td>
  </tr>
</table> </br>

<t><%= link_to 'Agendas', cliente_agendas_path(@cliente), class: "action_button" %> </t>
<t><%= link_to 'Orçamentos', cliente_orcamentos_path(@cliente), class: "action_button" %> </t>
</br></br>
<t><%= link_to 'Editar', edit_cliente_path(@cliente), class: "action_button" %> </t>
<t><%= link_to 'Voltar', clientes_path, class: "action_button" %> </t>