config/routes.rb
ClimatizanetT2::Application.routes.draw do
  
  resources :equipamentos

  resources :orcamentos do
    resources :items
  end

  resources :items

  resources :orcamentos

  resources :clientes

  resources :usuarios

  resources :clientes do
    resources :agendas
  end

  resources :clientes do
    resources :orcamentos
  end

  
  resources :agendas

  resource :user_sessions, only: [:create, :new, :destroy]

  root 'home#index'

end

app/models/equipamento.rb
class Equipamento < ActiveRecord::Base

	belongs_to :usuario

	validates_presence_of :descricao

	validates_uniqueness_of :descricao

	def self.search(query)
		if query.present?
			where(['descricao ILIKE :query ', query: "%#{query}%"])
		else
			scoped
		end
	end
end

app/controllers/equipamentos_controller.rb
class EquipamentosController < ApplicationController
  before_action :set_equipamento, only: [:show, :edit, :update, :destroy]
  before_action :require_authentication, only: [:index, :new, :edit, :show, :create, :update, :destroy]

  # GET /equipamentos
  # GET /equipamentos.json
  def index
    @search_query = params[:q]

    @equipamentos = usuario_corrente.equipamentos.search(@search_query)
  end

  # GET /equipamentos/1
  # GET /equipamentos/1.json
  def show
    @equipamento = usuario_corrente.equipamentos.find(params[:id])
  end

  # GET /equipamentos/new
  def new
    @equipamento = usuario_corrente.equipamentos.build
  end

  # GET /equipamentos/1/edit
  def edit
    @equipamento = usuario_corrente.equipamentos.find(params[:id]) 
  end

  # POST /equipamentos
  # POST /equipamentos.json
  def create
    @equipamento = usuario_corrente.equipamentos.build(equipamento_params)

    if @equipamento.save
      #O métodoredirect_toenvia ao browser do usuário um código de resposta
      #“302” que signi!ca “Moved Temporarily”, dizendo ao navegador que ele deve ir para
      #outro endereço. tambem estamos escrevendo uma mensagem via "flash", 
      # Quando você escreve no flash, o conteúdo só estará disponível na próxima requisição. Por isso, é
      #normalmente utilizado em conjunto com redireções.
      redirect_to @equipamento, notice: 'Equipamento criado com sucesso!'
    else
      #redirecionar, perdemos todos os parâmetros que o usuário enviou e também as mensagens
      #de erro de validação quando executamos o método #save. Para essas
      #situações, devemos usar o#render, que não causa o redirecionamento.
      render action: 'new'
    end
  end

  # PATCH/PUT /equipamentos/1
  # PATCH/PUT /equipamentos/1.json
  def update
    @equipamento = usuario_corrente.equipamentos.find(params[:id])

    if @equipamento.update(equipamento_params)
      redirect_to @equipamento, notice: 'Equipamento alterado com sucesso!'
    else
      render action: 'edit'
    end
  end

  # DELETE /equipamentos/1
  # DELETE /equipamentos/1.json
  def destroy
    @equipamento = usuario_corrente.equipamentos.find(params[:id])
    @equipamento.destroy
      redirect_to equipamentos_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipamento
      @equipamento = Equipamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipamento_params
      params.require(:equipamento).permit(:descricao, :marca, :fornecedor, :potencia, :tipo, :modelo, :info)
    end
end

app/helpers/equipamentos_helper.rb
module EquipamentosHelper
end

app/views/equipamentos/_form.html.erb
<%= form_for(@equipamento) do |f| %>
  <% if @equipamento.errors.any? %>
    <div id="error_explanation">
      <h2>Erro ao salvar registro! Favor verificar.</h2>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Descrição" %>
    <%= f.text_field :descricao %>
    <%= error_tag @equipamento, :descricao %>
  </div>
  <div class="field">
    <%= f.label "Marca" %>
    <%= f.text_field :marca %>
    <%= error_tag @equipamento, :marca %>
  </div>
  <div class="field">
    <%= f.label "Fornecedor" %>
    <%= f.text_field :fornecedor %>
    <%= error_tag @equipamento, :fornecedor %>
  </div>
  <div class="field">
    <%= f.label "Potência" %>
    <%= f.text_field :potencia %>
    <%= error_tag @equipamento, :potencia %>
  </div>
  <div class="field">
    <%= f.label "Tipo" %>
    <%= f.text_field :tipo %>
    <%= error_tag @equipamento, :tipo %>
  </div>
  <div class="field">
    <%= f.label "Modelo" %>
    <%= f.text_field :modelo %>
    <%= error_tag @equipamento, :modelo %>
  </div>
  <div class="field">
    <%= f.label "Informações Adicionais" %>
    <%= f.text_area :info %>
    <%= error_tag @equipamento, :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipamentos/edit.html.erb
<h1>Editar Equipamento</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @equipamento, class: "action_button" %> 
<%= link_to 'Voltar', equipamentos_path, class: "action_button" %>

app/views/equipamentos/index.html.erb
<h1 class="title"> Equipamentos </h1>


<% @equipamentos.each do |equipamento| %>
  <article class="equipamento">
    <p>
      <h2><%= link_to equipamento.descricao, equipamento , id: "titleArt",  class: "titleArt" %></h2>
        <p class="created">
          <%= equipamento.marca %>
        </p>
        <p class="created">
          <%= equipamento.modelo %>
        </p>
    </p>
        <t><%= link_to 'Mostrar', equipamento ,  class: "action_button" %></t>
        <t><%= link_to 'Editar', edit_equipamento_path(equipamento) , class: "action_button" %></t>
        <t><%= link_to 'Excluir', equipamento, method: :delete, data: { confirm: 'Você realmente deseja excluir?' },  class: "action_button" %></t>
  </article>
<% end %>


<br>

<%= link_to 'Novo', new_equipamento_path ,  id: "newButton",  class: "newButton"%>

app/views/equipamentos/new.html.erb
<h1>Novo</h1>

<%= render 'form' %>

<%= link_to 'Voltar', equipamentos_path , class: "action_button"%>

app/views/equipamentos/show.html.erb
 <h1 id="title" class="title"> <%= @equipamento.descricao %></h1>

<table  id="showTable" class="showTable">
  <tr>
    <td><strong>Marca:</strong></td>
    <td><%= @equipamento.marca %></td>
  </tr>

  <tr>
    <td><strong>Fornecedor:</strong></td>
    <td><%= @equipamento.fornecedor %></td>
  </tr>

  <tr>
    <td><strong>Potência:</strong></td>
    <td><%= @equipamento.potencia %></td>
  </tr>

  <tr>
    <td><strong>Tipo:</strong></td>
    <td><%= @equipamento.tipo %></td>
  </tr>

  <tr>
    <td><strong>Modelo:</strong></td>
    <td><%= @equipamento.modelo %><td>
  </tr>

  <tr>
    <td><strong>Informações adicionais:</strong></td>
    <td><%= @equipamento.info %></td>
  </tr>
</table> </br>
<%= link_to 'Editar', edit_equipamento_path(@equipamento),  class: "action_button" %> 
<%= link_to 'Voltar', equipamentos_path,  class: "action_button" %>