config/routes.rb
ClimatizanetT2::Application.routes.draw do
  
  resources :equipamentos

  resources :orcamentos do
    resources :items
  end

  resources :items

  resources :orcamentos

  resources :clientes

  resources :usuarios

  resources :clientes do
    resources :agendas
  end

  resources :clientes do
    resources :orcamentos
  end

  
  resources :agendas

  resource :user_sessions, only: [:create, :new, :destroy]

  root 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

	belongs_to :orcamento

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :require_authentication, only: [:index, :new, :edit, :show, :create, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    orcamento = Orcamento.find(params[:orcamento_id])

    @items = orcamento.items
    @orcamento = orcamento
  end

  # GET /items/1
  # GET /items/1.json
  def show
    orcamento = Orcamento.find(params[:orcamento_id])

    @item = orcamento.items.find(params[:id]) 
    @items = orcamento.items
    @orcamento = orcamento
  end

  # GET /items/new
  def new
    orcamento = Orcamento.find(params[:orcamento_id])

    @item = orcamento.items.build
    @items = orcamento.items
    @orcamento = orcamento
  end

  # GET /items/1/edit
  def edit
    orcamento = Orcamento.find(params[:orcamento_id])

    @item = orcamento.items.find(params[:id]) 
    @items = orcamento.items
    @orcamento = orcamento
  end

  # POST /items
  # POST /items.json
  def create
    orcamento = Orcamento.find(params[:orcamento_id])

    @item = orcamento.items.create(item_params)
    @items = orcamento.items 
    @orcamento = orcamento
    redirect_to new_orcamento_item_path   
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    orcamento = Orcamento.find(params[:orcamento_id])
    @item = orcamento.items.find(params[:id])
    @items = orcamento.items 
    @orcamento = orcamento

    redirect_to new_orcamento_item_path
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    orcamento = Orcamento.find(params[:orcamento_id])
    @item = orcamento.items.find(params[:id])
    @orcamento = orcamento

    @item.destroy
    redirect_to new_orcamento_item_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:qtdequipamento, :qtdtubulacao, :qtdextra, :tubulacao, :extra, :valor, :descricao, :tipo_Servico, :tipo_produto, :produto, :potencia, :unidade_medida, :info)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for([@item.orcamento, @item]) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2> Erro ao salvar registro! Favor verificar. </h2>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Descrição" %>
    <%= f.text_field :descricao %>
    <%= error_tag @item, :descricao %>
  </div>

  <div class="select">
    <%= f.label "Equipamento" %>
    <%= f.select :produto, ['Split','Janeleiro', 'VRF', 'Central', 'Água Gelada', 'Outros'] %>
    <%= error_tag @item, :produto %>
  </div></br>
  
  <div class="field">
    <%= f.label "Quantidade" %>
    <%= f.number_field :qtdequipamento %>
    <%= error_tag @item, :qtdequipamento %>
  </div>
  
  <div class="select">
    <%= f.label "Tipo serviço" %>
    <%= f.select :tipo_Servico, ['Instalação', 'Manutenção','Assistência', 'Retirada', 'Tranferência','Outros'] %>
    <%= error_tag @item, :tipo_Servico %>
  </div> </br>
  
  <div class="select">
    <%= f.label "Tipo produto" %>
    <%= f.select :tipo_produto, ['Equipamento','Tubulação', 'Hidráulica', 'Elétrica','Outros'] %>
    <%= error_tag @item, :tipo_produto %>
   </div></br>
  
  <div class="select">
    <%= f.label "Potência" %>
    <%= f.select :potencia, ['1','5', '10', '20', '50', '100', '7.000','9.000','12.000','18.000','22.000','24.000','30.000','36.000','48.000','60.000','80.000','90.0000', 'Outros'] %>
    <%= error_tag @item, :potencia %>
  </div></br>
  
  <div class="select">
    <%= f.label "Unidade de medida" %>
    <%= f.select :unidade_medida, ['BTU/H','TR','Outros'] %>
    <%= error_tag @item, :unidade_medida %>
  </div> </br>

  <div class="select">
    <%= f.label "Tubulação" %>
    <%= f.select :tubulacao,['1/4 e 3/8', '1/4 e 1/2', '1/4 e 5/8', '1/4 e 3/4', '3/8 e 1/2', '3/8 e 5/8', '3/8 e 3/4', '3/8 e 1"','3/8 e 1+1/8'] %>
    <%= error_tag @item, :tubulacao %>
  </div> </br>
  
  <div class="field">
    <%= f.label "Quantidade de tubulação" %>
    <%= f.number_field :qtdtubulacao %>
    <%= error_tag @item, :qtdtubulacao %>
  </div>
  
  <div class="field">
    <%= f.label "Extras" %>
    <%= f.text_field :extra %>
    <%= error_tag @item, :extra %>
  </div>
  
  <div class="field">
    <%= f.label "Quantidade extra" %>
    <%= f.number_field :qtdextra %>
    <%= error_tag @item, :qtdextra %>
  </div>
  
  <div class="field">
    <%= f.label "Valor" %>
    <%= f.number_field :valor %>
    <%= error_tag @item, :valor %>

  <div class="field">
    <%= f.label "Informações adicionais" %>
    <%= f.text_area :info %>
    <%= error_tag @item, :info %>
  </div>

  <div class="select">
    <%= f.label "Situação" %>
    <%= f.select :situacao, ['Ativo','Inativo'] %>
    <%= error_tag @item, :situacao %>
  </div> </br>

  </br>
  <div class="actions">
    <%= f.submit %>
  </div></br>

<% end %>

app/views/items/edit.html.erb
<h1>Editar itens</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', [@item.orcamento, @item] , class: "action_button"%>
<%= link_to 'Voltar', orcamento_items_path(@item.orcamento) , class: "action_button"%>

app/views/items/index.html.erb
<h1>Itens</h1>

<% @items.each do |item| %>
  <article class="item">
    <p class="created">
      <%= item.descricao %>
    </p>
    <p class="created">
      <%= item.qtdequipamento %>
    </p>
    <p class="created">
      <%= item.qtdtubulacao %>
    </p>
    <p class="created">
      <%= item.qtdextra %>
    </p>
    <p class="created">
      <%= item.tubulacao %>
    </p>
    <p class="created">
      <%= item.extra %>
    </p>
    <p class="created">
      <%= item.valor %>
    </p>
    <t><%= link_to 'Mostrar', [item.orcamento, item] , class: "action_button" %></t>
    <t><%= link_to 'Editar', edit_orcamento_item_path(item.orcamento, item) ,  class: "action_button" %></t>
    <t><%= link_to 'Excluir',  [item.orcamento, item], method: :delete, data: { confirm: 'Você realmente deseja excluir?' },  class: "action_button" %></t>
  </article>
<% end %>


<br>

<%= link_to 'Nova item', new_orcamento_item_path, id: "newButton",  class: "newButton"%>

app/views/items/new.html.erb
<p id="title" class="title">
  <%= @item.orcamento.cliente.nome %>
</p> <br>

<p id="title" class="title">
  <t> Orçamento: </t>
  <%= @item.orcamento.id %> </br>
  <%= @item.orcamento.descricao %>
</p>

</br>

<h1>Novo item</h1>

</br>

<%= render 'form' %>

</br>

<% @items.each do |item| %>
    <% if item.descricao.present? %>
     <table  id="showTable" class="showTable">
        <tr>
          <td><strong>Descrição:</strong></td>
          <td><%= item.descricao %></td>
        </tr>

        <tr>
          <td><strong>Equipamento:</strong></td>
          <td><%= item.produto %></td>
        </tr>

        <tr>
          <td><strong>Quantidade:</strong></td>
          <td><%= item.qtdequipamento %></td>
        </tr>

        <tr>
          <td><strong>Tipo de serviço:</strong></td>
          <td><%= item.tipo_Servico %></td>
        </tr>

        <tr>
          <td><strong>Tipo de produto:</strong></td>
          <td><%= item.tipo_produto %><td>
        </tr>

        <tr>
          <td><strong>Potência:</strong></td>
          <td><%= item.potencia %></td>
        </tr>
          <tr>
          <td><strong>Unidade de medida:</strong></td>
          <td><%= item.unidade_medida %></td>
        </tr>

        <tr>
          <td><strong>Tubulação:</strong></td>
          <td><%= item.tubulacao %></td>
        </tr>

        <tr>
          <td><strong>Potência:</strong></td>
          <td><%= item.potencia %></td>
        </tr>

        <tr>
          <td><strong>Quantidade de tubulação:</strong></td>
          <td><%= item.qtdtubulacao %></td>
        </tr>

        <tr>
          <td><strong>Extras:</strong></td>
          <td><%= item.extra %><td>
        </tr>

        <tr>
          <td><strong>Quantidade de extras:</strong></td>
          <td><%= item.qtdextra %></td>
        </tr>
        
          <tr>
          <td><strong>Valor:</strong></td>
          <td><%= item.valor %></td>
        </tr>
        
        <tr>
          <td><strong>Informações adicionais:</strong></td>
          <td><%= item.info %></td>
        </tr>

        <tr>
          <td>&nbsp;</td>
        </tr>

        <tr>
          <td><%= link_to 'Excluir',  [item.orcamento, item], method: :delete, data: { confirm: 'Você realmente deseja excluir?' },  class: "action_button" %></td>
        </tr>
      </table>  
  <% end %>
<% end %>

</br>
<%= link_to 'Voltar', cliente_orcamentos_path(@item.orcamento.cliente) , class: "action_button"%>

app/views/items/show.html.erb
<p>
  <strong>Qtdequipamento:</strong>
  <%= @item.descricao %>
</p>
<p>
  <strong>Qtdequipamento:</strong>
  <%= @item.qtdequipamento %>
</p>

<p>
  <strong>Qtdtubulacao:</strong>
  <%= @item.qtdtubulacao %>
</p>

<p>
  <strong>Qtdextra:</strong>
  <%= @item.qtdextra %>
</p>

<p>
  <strong>Tubulacao:</strong>
  <%= @item.tubulacao %>
</p>

<p>
  <strong>Extra:</strong>
  <%= @item.extra %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @item.valor %>
</p>

<%= link_to 'Editar', edit_orcamento_item_path(@item.orcamento, @item) , class: "action_button"%> |
<%= link_to 'Voltar', orcamento_items_path(@item.orcamento) , class: "action_button"%>