config/routes.rb
ClimatizanetT2::Application.routes.draw do
  
  resources :equipamentos

  resources :orcamentos do
    resources :items
  end

  resources :items

  resources :orcamentos

  resources :clientes

  resources :usuarios

  resources :clientes do
    resources :agendas
  end

  resources :clientes do
    resources :orcamentos
  end

  
  resources :agendas

  resource :user_sessions, only: [:create, :new, :destroy]

  root 'home#index'

end

app/views/layouts/_user_navbar.erb
<NAV>
	<ul>
		<li><%= link_to "Agenda", agendas_path %></li>
		<li><%= link_to "Cliente", clientes_path %></li>
		<li><%= link_to "Equipamento", equipamentos_path %></li>
		<li><%= link_to "Logout",  user_sessions_path(@post), method: "delete" %></li>
	</ul>
</NAV>	

app/views/layouts/_visitor_navbar.erb
<NAV>
	<ul>
		<li><%= link_to "Login", new_user_sessions_path %></li>
	</ul>
</NAV>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClimatizaNet</title>
	<!-- <link rel="stylesheet" type="text/css"  href="http://fonts.googleapis.com/css?family=Ubuntu"> -->
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Audiowide">
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>

<body>
	<header>
		<div id="header-wrap">
			<h1><%= link_to "ClimatizaNet", root_path %></h1>
			<% if usuario_logado? %>
				<%= render'layouts/user_navbar'%>
			<% else%>
				<%= render'layouts/visitor_navbar'%>
			<% end%>
		</div>
	</header>	

	<div id="content">
		<% if notice.present? %>
			<p id="notice"><%= notice %></p>
		<% end%>

		<% if alert.present? %>
			<p id="alert"><%= alert %></p>
		<% end%>

			<!--O que difere layouts de templates de ações é a execução do comando yield.
				O yield diz ao Rails que, naquele exato ponto, deverá ser injetado um outro template. 
				É possível também ter mais de um layout em um sistema. Isso é útil, por exemplo,
			quando há diversas “personas” em um site, como um administrador e um usuário
			comum, ou um lojista e o cliente.-->
		<%= yield%>
	</div>

</body>
</html>